# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "da8ffb5750c5a9095cd1932b58d47a24"
name = "Experion Blogs"
handle = "blog-filter-sort"
application_url = "https://date-salmon-ahead-isaac.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_metaobject_definitions,read_metaobjects,write_content,write_metaobject_definitions,write_metaobjects,read_products,write_products"

[auth]
redirect_urls = [
  "https://date-salmon-ahead-isaac.trycloudflare.com/auth/callback",
  "https://date-salmon-ahead-isaac.trycloudflare.com/auth/shopify/callback",
  "https://date-salmon-ahead-isaac.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
